CREATE LOGIN [infce]
    WITH PASSWORD = N'#nqwbTwk{f4j|iHc>dusiaizmsFT7_&#$!~<lUcAMfmiqzgq', SID = 0x1DB085DD4F7C754BA5EA9EA4C22EF46D, DEFAULT_DATABASE = [MCLLIVE], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

