CREATE LOGIN [interface]
    WITH PASSWORD = N'Mnqwb{fIj|DipRcudiazlcfqmsFT7_&#$!~<mDiqzg#CdjzE', SID = 0xC21463AC45A4CC40B90A1C1CF3CDBBB5, DEFAULT_DATABASE = [INTERFACES], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

