CREATE TABLE [dbo].[data_catalog_20130305] (
    [TEST MNEMONIC]     NVARCHAR (255) NULL,
    [TEST NAME]         NVARCHAR (255) NULL,
    [MESSAGE]           NVARCHAR (255) NULL,
    [TEST ALIAS]        NVARCHAR (255) NULL,
    [CPT CODES]         NVARCHAR (255) NULL,
    [INCLUDES]          NVARCHAR (255) NULL,
    [PREF SPECIMEN]     NVARCHAR (255) NULL,
    [MIN VOL]           NVARCHAR (255) NULL,
    [OTH SPEC]          NVARCHAR (255) NULL,
    [INSTRUCTIONS]      NVARCHAR (255) NULL,
    [CONTAINER]         NVARCHAR (255) NULL,
    [TRANS TEMP]        NVARCHAR (255) NULL,
    [SPEC STAB]         NVARCHAR (255) NULL,
    [REJ CRIT]          NVARCHAR (255) NULL,
    [METHODOLOGY]       NVARCHAR (255) NULL,
    [FDA STAT]          NVARCHAR (255) NULL,
    [SETUP SCHD]        NVARCHAR (255) NULL,
    [REP AVAIL(HRS)]    NVARCHAR (255) NULL,
    [LIMITATIONS]       NVARCHAR (255) NULL,
    [REF RANGE]         NVARCHAR (255) NULL,
    [CLIN SIGNIFICANCE] NVARCHAR (255) NULL
);

