CREATE TABLE [dbo].[ins_backup] (
    [rowguid]              UNIQUEIDENTIFIER NOT NULL,
    [deleted]              BIT              NOT NULL,
    [account]              VARCHAR (15)     NOT NULL,
    [ins_a_b_c]            VARCHAR (1)      NOT NULL,
    [holder_nme]           VARCHAR (40)     NULL,
    [holder_dob]           DATETIME         NULL,
    [holder_sex]           VARCHAR (1)      NULL,
    [holder_addr]          VARCHAR (40)     NULL,
    [holder_city_st_zip]   VARCHAR (40)     NULL,
    [plan_nme]             VARCHAR (45)     NULL,
    [plan_addr1]           VARCHAR (40)     NULL,
    [plan_addr2]           VARCHAR (40)     NULL,
    [p_city_st]            VARCHAR (40)     NULL,
    [policy_num]           VARCHAR (50)     NULL,
    [cert_ssn]             VARCHAR (15)     NULL,
    [grp_nme]              VARCHAR (50)     NULL,
    [grp_num]              VARCHAR (15)     NULL,
    [employer]             VARCHAR (25)     NULL,
    [e_city_st]            VARCHAR (35)     NULL,
    [fin_code]             VARCHAR (1)      NULL,
    [ins_code]             VARCHAR (10)     NULL,
    [relation]             VARCHAR (2)      NULL,
    [mod_date]             DATETIME         NOT NULL,
    [mod_user]             VARCHAR (50)     NOT NULL,
    [mod_prg]              VARCHAR (50)     NOT NULL,
    [mod_host]             VARCHAR (50)     NOT NULL,
    [holder_lname]         VARCHAR (40)     NULL,
    [holder_fname]         VARCHAR (40)     NULL,
    [holder_mname]         VARCHAR (40)     NULL,
    [plan_effective_date]  DATETIME         NULL,
    [plan_expiration_date] DATETIME         NULL
);

