CREATE TABLE [dbo].[pat_ub_update] (
    [rowguid]                   UNIQUEIDENTIFIER NOT NULL,
    [deleted]                   BIT              NOT NULL,
    [account]                   VARCHAR (15)     NOT NULL,
    [ssn]                       VARCHAR (11)     NULL,
    [pat_addr1]                 VARCHAR (40)     NULL,
    [pat_addr2]                 VARCHAR (40)     NULL,
    [city_st_zip]               VARCHAR (40)     NULL,
    [dob_yyyy]                  DATETIME         NULL,
    [sex]                       VARCHAR (1)      NULL,
    [relation]                  VARCHAR (2)      NULL,
    [guarantor]                 VARCHAR (40)     NULL,
    [guar_addr]                 VARCHAR (40)     NULL,
    [g_city_st]                 VARCHAR (40)     NULL,
    [pat_marital]               VARCHAR (1)      NULL,
    [icd9_1]                    VARCHAR (7)      NULL,
    [icd9_2]                    VARCHAR (7)      NULL,
    [icd9_3]                    VARCHAR (7)      NULL,
    [icd9_4]                    VARCHAR (7)      NULL,
    [icd9_5]                    VARCHAR (7)      NULL,
    [icd9_6]                    VARCHAR (7)      NULL,
    [icd9_7]                    VARCHAR (7)      NULL,
    [icd9_8]                    VARCHAR (7)      NULL,
    [icd9_9]                    VARCHAR (7)      NULL,
    [pc_code]                   INT              NULL,
    [mailer]                    VARCHAR (1)      NULL,
    [first_dm]                  DATETIME         NULL,
    [last_dm]                   DATETIME         NULL,
    [min_amt]                   MONEY            NULL,
    [phy_id]                    VARCHAR (15)     NULL,
    [dbill_date]                DATETIME         NULL,
    [ub_date]                   DATETIME         NULL,
    [h1500_date]                DATETIME         NULL,
    [colltr_date]               DATETIME         NULL,
    [baddebt_date]              DATETIME         NULL,
    [batch_date]                DATETIME         NULL,
    [guar_phone]                VARCHAR (13)     NULL,
    [bd_list_date]              DATETIME         NULL,
    [ebill_batch_date]          DATETIME         NULL,
    [ebill_batch_1500]          DATETIME         NULL,
    [e_ub_demand]               BIT              NOT NULL,
    [e_ub_demand_date]          DATETIME         NULL,
    [claimsnet_1500_batch_date] DATETIME         NULL,
    [claimsnet_ub_batch_date]   DATETIME         NULL,
    [mod_date]                  DATETIME         NOT NULL,
    [mod_user]                  VARCHAR (50)     NOT NULL,
    [mod_prg]                   VARCHAR (50)     NOT NULL,
    [mod_host]                  VARCHAR (50)     NOT NULL
);

