using LabBilling.Core.DataAccess;
using LabBilling.Core.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace LabBilling.Core.Services;
public interface IAccountService
{
    event EventHandler<AccountEventArgs> AccountLockCleared;
    event EventHandler<AccountEventArgs> AccountLocked;
    event EventHandler<AccountEventArgs> AccountValidated;
    event EventHandler<ValidationUpdatedEventArgs> ValidationAccountUpdated;

    Account Add(Account table);
    Task<object> AddAsync(Account table);
    Account AddCharge(Account accData, string cdm, int qty, DateTime serviceDate, string comment = null, string refNumber = null, double miscAmount = 0);
    Chrg AddCharge(Chrg chrg);
    Account AddCharge(string account, string cdm, int qty, DateTime serviceDate, string comment = null, string refNumber = null, double miscAmount = 0);
    Task<Account> AddChargeAsync(Account accData, string cdm, int qty, DateTime serviceDate, string comment = null, string refNumber = null, double miscAmount = 0);
    Task<Account> AddChargeAsync(string account, string cdm, int qty, DateTime serviceDate, string comment = null, string refNumber = null, double miscAmount = 0);
    ChrgDetail AddChargeModifier(int chrgDetailId, string modifier);
    IList<AccountNote> AddNote(string accountNo, string noteText);
    Task<IList<AccountNote>> AddNoteAsync(string account, string noteText);
    Chk AddPayment(Chk chk);
    void AddRecentlyAccessedAccount(string accountNo, string userName);
    Account BundlePanels(Account account);
    Task<Account> BundlePanelsAsync(Account account);
    bool ChangeClient(Account model, string newClientMnem);
    Task<bool> ChangeClientAsync(Account table, string newClientMnem);
    Account ChangeDateOfService(Account model, DateTime newDate, string reason_comment);
    Task<Account> ChangeDateOfServiceAsync(Account table, DateTime newDate, string reason_comment);
    Account ChangeFinancialClass(Account model, string newFinCode);
    Account ChangeFinancialClass(string accountNo, string newFinCode);
    Task<Account> ChangeFinancialClassAsync(Account model, string newFinCode);
    Task<Account> ChangeFinancialClassAsync(string accountNo, string newFinCode);
    bool ClearAccountLock(Account account);
    bool ClearAccountLock(int id);
    bool ClearAccountLocks(string username, string hostname);
    Account ClearClaimStatus(Account account);
    Task ClearClaimStatusAsync(Account account);
    Pat ClearCollectionsListDate(string accountNo);
    Chrg CreditCharge(int chrgId, string comment = "");
    bool DeleteInsurance(Ins ins);
    Account GetAccount(string account, bool demographicsOnly = false, bool secureLock = true);
    Task<Account> GetAccountAsync(string account, bool demographicsOnly = false);
    (bool locksuccessful, AccountLock lockInfo) GetAccountLock(string account);
    List<AccountLock> GetAccountLocks();
    Account GetAccountMinimal(string accountNo);
    IEnumerable<ClaimItem> GetAccountsForClaims(ClaimType claimType, int maxClaims = 0);
    Task<IEnumerable<ClaimItem>> GetAccountsForClaimsAsync(ClaimType claimType, int maxClaims = 0);
    double GetBalance(string accountNo);
    Chrg GetCharge(int chrgNo);
    IList<Chrg> GetCharges(string accountNo, bool showCredited = true, bool includeInvoiced = true, DateTime? asOfDate = null, bool excludeCBill = true);
    IList<ClaimChargeView> GetClaimCharges(string accountNo);
    List<ClaimItem> GetClaimItems(ClaimType claimType);
    IEnumerable<InvoiceSelect> GetInvoiceAccounts(string clientMnem, DateTime thruDate);
    Task<IEnumerable<InvoiceSelect>> GetInvoiceAccountsAsync(string clientMnem, DateTime thruDate);
    decimal GetNextAccountNumber();
    List<AccountNote> GetNotes(string accountNo);
    List<PatientStatementAccount> GetPatientStatements(string accountNo);
    Account InsuranceSwap(Account account, InsCoverage swap1, InsCoverage swap2);
    Task<Account> InsuranceSwapAsync(Account account, InsCoverage swap1, InsCoverage swap2);
    Chrg MoveCharge(string sourceAccount, string destinationAccount, int chrgId);
    Task MoveChargeAsync(string sourceAccount, string destinationAccount, int chrgId);
    (bool isSuccess, string error) MoveCharges(string sourceAccount, string destinationAccount);
    ChrgDetail RemoveChargeModifier(int chrgDetailId);
    IList<Chrg> ReprocessCharges(Account account, string comment);
    IList<Chrg> ReprocessCharges(string account, string comment);
    Task<IList<Chrg>> ReprocessChargesAsync(Account account, string comment);
    Task<IList<Chrg>> ReprocessChargesAsync(string account, string comment);
    Ins SaveInsurance(Ins ins);
    IList<AccountSearch> SearchAccounts(string lastName, string firstName, string mrn, string ssn, string dob, string sex, string accountSearch);
    Chrg SetChargeCreditFlag(int chrgId, bool flag);
    Pat SetCollectionsDate(Pat pat);
    bool SetNoteAlert(string account, bool showAlert);
    Task<bool> SetNoteAlertAsync(string account, bool showAlert);
    Account UnbundlePanels(Account account);
    Task<Account> UnbundlePanelsAsync(Account account);
    Account UpdateAccountDemographics(Account acc);
    IList<Chrg> UpdateChargesClient(string account, string clientMnem);
    Task<IList<Chrg>> UpdateChargesClientAsync(string account, string clientMnem);
    IList<Chrg> UpdateChargesFinCode(IList<Chrg> charges, string finCode);
    Task<IList<Chrg>> UpdateChargesFinCodeAsync(IList<Chrg> charges, string finCode);
    Account UpdateDiagnoses(Account acc);
    Task<Account> UpdateDiagnosesAsync(Account acc);
    ChrgDiagnosisPointer UpdateDiagnosisPointer(ChrgDiagnosisPointer ptr);
    Account UpdateStatementFlag(Account acc, string flag);
    Account UpdateStatus(Account model, string status);
    int UpdateStatus(string accountNo, string status);
    Task<Account> UpdateStatusAsync(Account model, string status);
    Task<int> UpdateStatusAsync(string accountNo, string status);
    Account Validate(Account account, bool reprint = false);
    Task<Account> ValidateAsync(Account account, bool reprint = false);
    void ValidateUnbilledAccounts();
    Task ValidateUnbilledAccountsAsync();
}