CREATE TABLE [zzz].[phy_deleted] (
    [rowguid]     UNIQUEIDENTIFIER NULL,
    [deleted]     BIT              NULL,
    [upin]        VARCHAR (6)      NULL,
    [ub92_upin]   VARCHAR (6)      NULL,
    [tnh_num]     VARCHAR (15)     NULL,
    [billing_npi] VARCHAR (15)     NULL,
    [pc_code]     VARCHAR (2)      NULL,
    [cl_mnem]     VARCHAR (15)     NULL,
    [last_name]   VARCHAR (30)     NULL,
    [first_name]  VARCHAR (30)     NULL,
    [mid_init]    VARCHAR (30)     NULL,
    [group1]      VARCHAR (35)     NULL,
    [addr_1]      VARCHAR (40)     NULL,
    [addr_2]      VARCHAR (40)     NULL,
    [city]        VARCHAR (30)     NULL,
    [state]       VARCHAR (2)      NULL,
    [zip]         VARCHAR (10)     NULL,
    [phone]       VARCHAR (40)     NULL,
    [reserved]    VARCHAR (1)      NULL,
    [num_labels]  INT              NULL,
    [mod_date]    DATETIME         NULL,
    [mod_user]    VARCHAR (40)     NULL,
    [mod_prg]     VARCHAR (40)     NULL,
    [uri]         NUMERIC (15)     NULL,
    [mt_mnem]     VARCHAR (15)     NULL,
    [credentials] VARCHAR (50)     NULL,
    [ov_code]     VARCHAR (50)     NULL
);

