-- ============================================================================
-- schema-fixups.sql  —  Phase 22-02 Task 2  (SQL-Server-ism fix-ups)
-- ----------------------------------------------------------------------------
-- Applies AFTER Database/Postgres/schema-tables.sql (the pgloader-generated DDL).
-- Run order (clean from scratch):
--   psql -f schema-tables.sql      (pgloader output: tables, indexes, PKs, FKs)
--   psql -f schema-fixups.sql      (this file: identities, computed cols, defaults)
--
-- What pgloader did NOT translate correctly, fixed here:
--   1. IDENTITY columns      -> GENERATED BY DEFAULT AS IDENTITY (integer types) or
--                               a sequence DEFAULT nextval(...) (numeric/decimal types,
--                               which PG IDENTITY cannot use). BY DEFAULT / nextval both
--                               allow explicit inserts (needed for Phase 25 data migration).
--   2. Computed columns      -> GENERATED ALWAYS AS (expr) STORED where deterministic;
--                               plain column where the T-SQL is non-deterministic or
--                               references a not-yet-ported UDF (documented inline).
--   3. T-SQL text defaults   -> pgloader-broken string-function/concat defaults were
--                               dropped during load; meaningful literal defaults and
--                               getdate()->now() defaults are re-applied here.
--   4. xml btree index       -> pgloader's CREATE INDEX on an xml column failed (xml has
--                               no btree opclass); recreated here as a functional index.
--
-- IDENTIFIER POLICY: original SQL Server casing preserved, every identifier double-quoted
-- (pgloader `quote identifiers`). All references below quote schema, table, and column.
-- ============================================================================

-- Make the uuid generator available for any clean-from-scratch apply that runs fixups
-- without the pgloader BEFORE-LOAD step.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1a. IDENTITY columns of INTEGER type -> GENERATED BY DEFAULT AS IDENTITY
--     (drop any pgloader serial default + owned sequence first, then add identity)
-- ============================================================================
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT * FROM (VALUES
      ('audit','audit_acc','uid'),
      ('audit','audit_aging_history','uid'),
      ('audit','audit_bad_debt','uid'),
      ('audit','audit_cdm','uid'),
      ('audit','audit_chk','uid'),
      ('audit','audit_chrg','uid'),
      ('audit','audit_cpt4','uid'),
      ('audit','audit_cpt4_2','uid'),
      ('audit','audit_cpt4_3','uid'),
      ('audit','audit_cpt4_4','uid'),
      ('audit','audit_cpt4_5','uid'),
      ('audit','audit_dbill','uid'),
      ('audit','audit_insc','uid'),
      ('audit','audit_pat','uid'),
      ('audit','audit_patdx','uid'),
      ('dbo','ACC_LMRP','uri'),
      ('dbo','AuditLog','ID'),
      ('dbo','chk_batch','BatchNo'),
      ('dbo','chk_electronic','uid'),
      ('dbo','chk_electronic_cpt_adjustment_codes','uid'),
      ('dbo','data_electronic_status','uid'),
      ('dbo','data_EOB','uid'),
      ('dbo','data_EOB_Detail','uid'),
      ('dbo','data_prior_month_ar','uid'),
      ('dbo','data_quest_360','uid'),
      ('dbo','data_quest_billing','uid'),
      ('dbo','data_quest_global_billing_tracking','uid'),
      ('dbo','dict_acc_validation','rule_id'),
      ('dbo','dict_acc_validation_criteria','uid'),
      ('dbo','dict_cdm_conversion','uid'),
      ('dbo','dict_claim_validation_rule_criteria','RuleCriteriaId'),
      ('dbo','dict_claim_validation_rules','RuleId'),
      ('dbo','dict_Date','ID'),
      ('dbo','error_prg','uid'),
      ('dbo','icd9desc','id'),
      ('dbo','insc_payor','uid'),
      ('dbo','job_track_wdk_del','uid'),
      ('dbo','monthlycharges_del','rowid'),
      ('dbo','patbill_acc','uid'),
      ('dbo','patdx','uid'),
      ('dbo','phy_sanc','uri'),
      ('dbo','pth','pc_code'),
      ('dbo','rpt_track','uri'),
      ('dbo','test_charges','charge_number'),
      ('dbo','Totals_TPG','uid'),
      ('dbo','TransactionDetail','TransactionDetailID'),
      ('dbo','UserProfile','Id'),
      ('dbo','wl_cat','uri'),
      ('dbo','XmlSourceTable','uid'),
      ('dict','menuitems','item_id'),
      ('dict','menuprofile','profile_id'),
      ('dictionary','mapping','uid'),
      ('zzz','dict_ViewerAccSql','uid')
    ) AS t(sch, tbl, col)
  LOOP
    -- Drop any pgloader serial default and its owned sequence.
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I DROP DEFAULT', r.sch, r.tbl, r.col);
    -- Convert to a real identity column (BY DEFAULT permits explicit inserts).
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', r.sch, r.tbl, r.col);
  END LOOP;
END $$;

-- Drop the now-orphaned pgloader serial sequences (were OWNED BY the columns above).
DROP SEQUENCE IF EXISTS dbo."ACC_LMRP_uri_seq";
DROP SEQUENCE IF EXISTS dbo."AuditLog_ID_seq";
DROP SEQUENCE IF EXISTS dbo."TransactionDetail_TransactionDetailID_seq";
DROP SEQUENCE IF EXISTS dbo."UserProfile_Id_seq";
DROP SEQUENCE IF EXISTS dbo."XmlSourceTable_uid_seq";
DROP SEQUENCE IF EXISTS dbo."chk_batch_BatchNo_seq";
DROP SEQUENCE IF EXISTS dbo.data_quest_360_uid_seq;
DROP SEQUENCE IF EXISTS dbo."dict_Date_ID_seq";
DROP SEQUENCE IF EXISTS dbo.dict_acc_validation_rule_id_seq;
DROP SEQUENCE IF EXISTS dbo.dict_acc_validation_criteria_uid_seq;
DROP SEQUENCE IF EXISTS dbo."dict_claim_validation_rule_criteria_RuleCriteriaId_seq";
DROP SEQUENCE IF EXISTS dbo."dict_claim_validation_rules_RuleId_seq";
DROP SEQUENCE IF EXISTS dbo.error_prg_uid_seq;
DROP SEQUENCE IF EXISTS dbo.insc_payor_uid_seq;
DROP SEQUENCE IF EXISTS dbo.job_track_wdk_del_uid_seq;
DROP SEQUENCE IF EXISTS dbo.monthlycharges_del_rowid_seq;
DROP SEQUENCE IF EXISTS dbo.phy_sanc_uri_seq;
DROP SEQUENCE IF EXISTS dbo.pth_pc_code_seq;
DROP SEQUENCE IF EXISTS dbo.rpt_track_uri_seq;
DROP SEQUENCE IF EXISTS dbo.test_charges_charge_number_seq;
DROP SEQUENCE IF EXISTS dbo.wl_cat_uri_seq;

-- ============================================================================
-- 1b. IDENTITY columns of NUMERIC/DECIMAL type -> sequence DEFAULT nextval(...)
--     PostgreSQL GENERATED ... AS IDENTITY requires an integer type, so the
--     numeric identity columns (e.g. chrg.chrg_num numeric(15,0)) keep their
--     numeric type for parity and get an owned sequence default. Explicit inserts
--     still work (the sequence is advanced via setval during Phase 25 migration).
-- ============================================================================
DO $$
DECLARE
  r record;
  seqname text;
BEGIN
  FOR r IN
    SELECT * FROM (VALUES
      ('audit','audit_amt','uri'),
      ('audit','audit_cli_dis','uri'),
      ('audit','audit_lmrp','audit_uid'),
      ('audit','audit_phy','audit_uri'),
      ('dbo','acc_dup_check','uid'),
      ('dbo','amt','uri'),
      ('dbo','chk','pay_no'),
      ('dbo','chrg','chrg_num'),
      ('dbo','chrg_err','uri'),
      ('dbo','chrg_nhc','chrg_num'),
      ('dbo','chrg_test','chrg_num'),
      ('dbo','chrg_testing_del','uri'),
      ('dbo','cli_dis','uri'),
      ('dbo','cpt4_audit','uri'),
      ('dbo','data_ErrLog','uri'),
      ('dbo','dict_quest_reference_lab_tests','uid'),
      ('dbo','phy','uri'),
      ('dbo','rds','uri'),
      ('dbo','ReChrg','urn'),
      ('dbo','temp_ssi_del','uri'),
      ('dbo','test_chk','pay_no'),
      ('dbo','test_chrg','chrg_num'),
      ('dictionary','lmrp','uid'),
      ('infce','messages_inbound','systemMsgId'),
      ('infce','messages_inbound_adt','systemMsgId'),
      ('infce','messages_inbound_webconnect','systemMsgId'),
      ('infce','messages_outbound','systemMsgId')
    ) AS t(sch, tbl, col)
  LOOP
    seqname := r.tbl || '_' || r.col || '_seq';
    -- PostgreSQL sequences must be an integer type; bigint nextval() assigns cleanly into
    -- the numeric(p,0) column. (numeric identity columns cannot use GENERATED AS IDENTITY.)
    EXECUTE format('CREATE SEQUENCE IF NOT EXISTS %I.%I AS bigint', r.sch, seqname);
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I SET DEFAULT nextval(%L)',
                   r.sch, r.tbl, r.col, quote_ident(r.sch) || '.' || quote_ident(seqname));
    EXECUTE format('ALTER SEQUENCE %I.%I OWNED BY %I.%I.%I', r.sch, seqname, r.sch, r.tbl, r.col);
  END LOOP;
END $$;

-- ============================================================================
-- 2. COMPUTED columns
-- ============================================================================
-- 2a. Deterministic -> GENERATED ALWAYS AS (expr) STORED
--     dbo.insc.fin_class = (fin_code)
ALTER TABLE dbo."insc" DROP COLUMN IF EXISTS "fin_class";
ALTER TABLE dbo."insc"
  ADD COLUMN "fin_class" varchar GENERATED ALWAYS AS ("fin_code") STORED;

--     dbo.tempChk.total = paid + contractual + write_off
ALTER TABLE dbo."tempChk" DROP COLUMN IF EXISTS "total";
ALTER TABLE dbo."tempChk"
  ADD COLUMN "total" numeric
  GENERATED ALWAYS AS (COALESCE("paid",0) + COALESCE("contractual",0) + COALESCE("write_off",0)) STORED;

--     dbo.tempDaily.error = (startBal + charges - payments) - endBal  (isnull -> coalesce)
ALTER TABLE dbo."tempDaily" DROP COLUMN IF EXISTS "error";
ALTER TABLE dbo."tempDaily"
  ADD COLUMN "error" numeric
  GENERATED ALWAYS AS (((COALESCE("startBal",0) + COALESCE("charges",0)) - COALESCE("payments",0)) - COALESCE("endBal",0)) STORED;

-- 2b. NON-deterministic / UDF-dependent -> kept as PLAIN columns (documented).
--     These cannot be GENERATED ... STORED in PostgreSQL:
--       * dbo.chrg.age_on_date_of_service  uses datediff(...getdate()...) -> non-deterministic
--         (STORED generated expressions must be IMMUTABLE; now()/getdate() is not).
--       * dbo.chrg.calc_amt = dbo.GetAmountTotal(chrg_num) * qty  -> references a T-SQL UDF
--         not yet ported to PostgreSQL (UDF port is Phase 23).
--     pgloader already left both as plain nullable columns (int / numeric), which is the
--     desired Phase-22 fallback. The real computed logic is restored in Phase 23 (UDF port +
--     trigger or view-computed column). No action needed here; recorded for traceability.

-- ============================================================================
-- 3. Re-apply meaningful column DEFAULTS dropped during load
-- ============================================================================
-- 3a. getdate() -> now()  on the audit "mod_date"/event-date timestamp columns that are
--     semantically defaulted. (Broad set; only applied where the column exists.)
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT n.nspname AS sch, c.relname AS tbl, a.attname AS col
    FROM pg_attribute a
    JOIN pg_class c ON a.attrelid=c.oid
    JOIN pg_namespace n ON c.relnamespace=n.oid
    WHERE c.relkind='r' AND a.attnum>0 AND NOT a.attisdropped
      AND n.nspname IN ('dbo','audit','dict','dictionary','infce','zzz','tst')
      AND a.attname IN ('mod_date','event_date','date_entered')
      AND format_type(a.atttypid,a.atttypmod) LIKE 'timestamp%'
  LOOP
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I SET DEFAULT now()', r.sch, r.tbl, r.col);
  END LOOP;
END $$;

-- 3b. Literal text/numeric defaults worth preserving (status flags, type codes, etc.).
ALTER TABLE dbo."acc"                      ALTER COLUMN "status"          SET DEFAULT 'NEW';
ALTER TABLE dbo."chk"                      ALTER COLUMN "status"          SET DEFAULT 'NEW';
ALTER TABLE dbo."chrg"                     ALTER COLUMN "status"          SET DEFAULT 'NEW';
ALTER TABLE dbo."chrg_unprocessed"         ALTER COLUMN "status"          SET DEFAULT 'NEW';
ALTER TABLE dbo."acc_location"             ALTER COLUMN "pt_type"         SET DEFAULT 'REF';
ALTER TABLE dbo."client"                   ALTER COLUMN "bill_pc_charges" SET DEFAULT 'NO';
ALTER TABLE dbo."client"                   ALTER COLUMN "late_notice"     SET DEFAULT 'N';
ALTER TABLE dbo."client"                   ALTER COLUMN "prn_loc"         SET DEFAULT 'Y';
ALTER TABLE dbo."cpt4"                     ALTER COLUMN "code_flag"       SET DEFAULT '*';
ALTER TABLE dbo."data_EOB"                 ALTER COLUMN "PatStat"         SET DEFAULT '0';
ALTER TABLE dbo."data_ErrLog"              ALTER COLUMN "App_Name"        SET DEFAULT '';
ALTER TABLE dbo."data_ErrLog"              ALTER COLUMN "Error_Msg"       SET DEFAULT '';
ALTER TABLE dbo."data_HL7_Msg"             ALTER COLUMN "msg_control_ID"  SET DEFAULT '';
ALTER TABLE dbo."data_HL7_Msg"             ALTER COLUMN "msg_status_reason" SET DEFAULT '';
ALTER TABLE dbo."dict_general_ledger_codes" ALTER COLUMN "gl_account_code" SET DEFAULT '001';
ALTER TABLE dbo."dict_general_ledger_codes" ALTER COLUMN "level_2"        SET DEFAULT '0000';
ALTER TABLE dbo."dict_general_ledger_codes" ALTER COLUMN "level_3"        SET DEFAULT '0000';
ALTER TABLE dbo."dict_global_billing_cdms" ALTER COLUMN "comment"        SET DEFAULT 'Original contract';
ALTER TABLE dbo."dict_reference_business"  ALTER COLUMN "performed_by"    SET DEFAULT 'QUEST';
ALTER TABLE dbo."emp"                      ALTER COLUMN "access"          SET DEFAULT 'NONE';
ALTER TABLE dbo."h1500"                    ALTER COLUMN "ins_abc"         SET DEFAULT 'A';
ALTER TABLE dbo."insc"                     ALTER COLUMN "claimsnet_payer_id" SET DEFAULT 'EXCLUDED';
ALTER TABLE dbo."Monthly_Reports"          ALTER COLUMN "button"          SET DEFAULT 'MAIN';
ALTER TABLE dbo."mutually_excl"            ALTER COLUMN "modi_indicator"  SET DEFAULT '0';
ALTER TABLE dbo."pat"                      ALTER COLUMN "icd_indicator"   SET DEFAULT 'I10';
ALTER TABLE dbo."pat"                      ALTER COLUMN "mailer"          SET DEFAULT 'N';
ALTER TABLE dbo."pat"                      ALTER COLUMN "pat_marital"     SET DEFAULT 'U';
ALTER TABLE dbo."phy"                      ALTER COLUMN "ub92_upin"       SET DEFAULT 'OTH000';
ALTER TABLE dbo."ub"                       ALTER COLUMN "ins_abc"         SET DEFAULT 'A';
-- SQL Server stored these as CONVERT(varchar(10),getdate(),101); the PG column is timestamp,
-- so default to now() (the formatted-string behaviour is a display concern, not storage).
ALTER TABLE dbo."Medicare_Accounts_Date_Time" ALTER COLUMN "mod_date"    SET DEFAULT now();
ALTER TABLE dbo."Medicare_Comm"            ALTER COLUMN "mod_date"        SET DEFAULT now();
ALTER TABLE dictionary."lmrp"              ALTER COLUMN "fincode"         SET DEFAULT 'A';
ALTER TABLE dictionary."lmrp"              ALTER COLUMN "payor"           SET DEFAULT 'MEDICARE';
ALTER TABLE infce."messages_inbound"             ALTER COLUMN "processFlag" SET DEFAULT 'N';
ALTER TABLE infce."messages_inbound_adt"         ALTER COLUMN "processFlag" SET DEFAULT 'N';
ALTER TABLE infce."messages_inbound_webconnect"  ALTER COLUMN "processFlag" SET DEFAULT 'N';

-- ============================================================================
-- 4. xml btree index that pgloader could not create
--    SQL Server: idx on infce.patient_demographics(xmlContents). xml has no btree opclass
--    in PostgreSQL; recreate as a functional index on the text cast so lookups still work.
-- ============================================================================
CREATE INDEX IF NOT EXISTS "idx_patient_demographics_xmlContents"
  ON infce."patient_demographics" (((("xmlContents")::text)));

-- ============================================================================
-- 5. Model<->schema reconciliation + search_path (folded in from the 22-05 smoke test)
--    The canonical DB-project schema is drifted vs the current .NET models; these
--    columns are mapped by the models (UserAccount, SysParameter) but were absent
--    from the translated schema. Add them so the data layer binds. (Phase 23 should
--    reconcile the broader model<->schema drift; see FINDINGS R3.)
-- ============================================================================
ALTER TABLE dbo."emp"    ADD COLUMN IF NOT EXISTS access_random_drug_screen boolean NOT NULL DEFAULT false;
ALTER TABLE dbo."system" ADD COLUMN IF NOT EXISTS "KeyName" varchar(50);

-- Models use unqualified table names, but tables live across 7 schemas. Set a
-- database-level search_path so unqualified resolution works. (Alternative for
-- Phase 23: set "Search Path" in the Npgsql connection string in AppEnvironment.)
ALTER DATABASE labbilling SET search_path = dbo, dictionary, dict, infce, audit, tst, zzz, public;
