/****** Object:  Stored Procedure dbo.sp_upd_dict_stats    Script Date: 9/19/2001 10:47:26 AM ******/
CREATE PROCEDURE [dbo].[sp_upd_dict_stats] AS

UPDATE STATISTICS cdm
UPDATE STATISTICS cdm_lab1
UPDATE STATISTICS cdw
UPDATE STATISTICS chrg_err
UPDATE STATISTICS cli_dis
UPDATE STATISTICS client
UPDATE STATISTICS emp
UPDATE STATISTICS fin
UPDATE STATISTICS icd9desc
UPDATE STATISTICS insc
UPDATE STATISTICS lmrp
UPDATE STATISTICS mutually_excl
UPDATE STATISTICS number
UPDATE STATISTICS phy
UPDATE STATISTICS phy_sanc
UPDATE STATISTICS pth
UPDATE STATISTICS revcode
UPDATE STATISTICS rds
UPDATE STATISTICS system
UPDATE STATISTICS unapp_panels
UPDATE STATISTICS zip
