CREATE VIEW dbo.vw_Acc_Pat_Indexed
WITH SCHEMABINDING
AS
    SELECT -- dbo.acc.rowguid ,
            a.deleted ,
            a.account ,
            a.pat_name ,
            a.cl_mnem ,
            a.fin_code ,
            a.trans_date ,
            a.status ,
            coalesce (a.ssn ,p.ssn) AS [ssn],
         --   num_comments ,
         --   meditech_account ,
            a.original_fincode ,
        --    oereqno ,
            a.mri ,
           -- post_date ,
            a.ov_order_id ,
            a.ov_pat_id ,
--            dbo.acc.mod_date ,
--            dbo.acc.mod_user ,
--            dbo.acc.mod_prg ,
--            dbo.acc.mod_host ,
            a.bill_priority ,
            a.guarantorID ,
            a.HNE_NUMBER ,
            a.trans_date_time ,
            a.tdate_update ,
            p.rowguid ,
         --   dbo.pat.deleted ,
          --  dbo.pat.account ,
            p.pat_full_name ,
          --  dbo.pat.ssn ,
            p.pat_addr1 ,
            p.pat_addr2 ,
            p.city_st_zip ,
            p.pat_city ,
            p.pat_state ,
            p.pat_zip ,
            p.dob_yyyy ,
            p.sex ,
            p.relation ,
            p.guarantor ,
            p.guar_addr ,
            p.g_city_st ,
            p.guar_city ,
            p.guar_state ,
            p.guar_zip ,
            p.pat_marital ,
            p.pat_race ,
            p.pat_phone ,
            p.icd9_1 ,
            p.icd9_2 ,
            p.icd9_3 ,
            p.icd9_4 ,
            p.icd9_5 ,
            p.icd9_6 ,
            p.icd9_7 ,
            p.icd9_8 ,
            p.icd9_9 ,
            p.pc_code ,
            p.mailer ,
            p.first_dm ,
            p.last_dm ,
            p.min_amt ,
            p.phy_id ,
            p.phy_comment ,
            p.dbill_date ,
            p.ub_date ,
            p.h1500_date ,
            p.ssi_batch ,
            p.colltr_date ,
            p.baddebt_date ,
            p.batch_date ,
            p.guar_phone ,
            p.bd_list_date ,
            p.ebill_batch_date ,
            p.ebill_batch_1500 ,
            p.e_ub_demand ,
            p.e_ub_demand_date ,
            p.claimsnet_1500_batch_date ,
            p.claimsnet_ub_batch_date ,
            p.mod_date ,
            p.mod_user ,
            p.mod_prg ,
            p.mod_host ,
            p.hne_epi_number ,
            p.location ,
            p.pat_email ,
            p.icd_indicator
    FROM dbo.acc  AS a
    INNER JOIN dbo.pat AS p ON a.account = p.account
    WHERE a.deleted = 0 AND p.deleted = 0
 --   order BY acc.trans_date, acc.account

GO
CREATE UNIQUE CLUSTERED INDEX [IDX_VW_ACC_PAT_INDEXED]
    ON [dbo].[vw_Acc_Pat_Indexed]([account] ASC, [rowguid] ASC) WITH (STATISTICS_NORECOMPUTE = ON);

